# Generated by Django 3.0.7 on 2020-06-07 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_auto_20200605_1053'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.Semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
