# Generated by Django 3.0.7 on 2020-06-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_auto_20200605_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='colour',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
